var SOURCE_ID = 'french-manga';
var BASES = ['https://w16.french-manga.net', 'https://french-manga.net'];
var SITE = BASES[0];
var UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/125 Safari/537.36';
function dec(s) { try { return decodeURIComponent(String(s || '')); } catch (_) { return String(s || ''); } }
function abs(u, base) { try { return absUrl(u, base); } catch (_) { try { return new URL(u, base).toString(); } catch (_) { return u; } } }
function clean(s) { return htmlText(String(s || '').replace(/<script[\s\S]*?<\/script>/gi, '')); }
function esc(s) { return encodeURIComponent(String(s || '')); }
function parseJson(r) { try { return JSON.parse((r && r.body) || ''); } catch (_) { return null; } }
function responseBody(r) { return r && (r.body || (typeof r.text === 'function' ? r.text() : '')) || ''; }
function uniq(a) { var out = [], seen = {}; (a || []).forEach(function (x) { if (x && !seen[x]) { seen[x] = true; out.push(x); } }); return out; }
function idOf(url) { var m = String(url || '').match(/[?&]newsid=(\d+)/i) || String(url || '').match(/\/(\d+)-/); return m ? m[1] : ''; }
function titleFromUrl(url) { return dec(String(url || '').split('/').pop().replace(/\.html.*$/, '').replace(/^\d+-/, '').replace(/[+_-]+/g, ' ')); }
function request(path, opts) {
  opts = opts || {}; var candidates = BASES.map(function (b) { return String(path).indexOf('http') === 0 ? path.replace(/^https?:\/\/[^/]+/, b) : b + (String(path).charAt(0) === '/' ? path : '/' + path); });
  return (function next(i) { if (i >= candidates.length) return Promise.resolve(null); return fetch(candidates[i], { method: opts.method || 'GET', headers: Object.assign({ 'User-Agent': UA, 'Referer': SITE + '/' }, opts.headers || {}), body: opts.body, timeoutMs: opts.timeoutMs || 12000 }).then(function (r) { if (r && r.status >= 200 && r.status < 400) { SITE = BASES[i]; return r; } return next(i + 1); }).catch(function () { return next(i + 1); }); })(0);
}
function cards(html, base) {
  var out = [], re = /short-poster[^>]*href=["']([^"']+)["'][^>]*alt=["']([^"']*)["']/gi, m;
  while ((m = re.exec(html || ''))) { var chunk = String(html).slice(m.index, m.index + 1600), im = chunk.match(/<img[^>]*(?:src|data-src)=["']([^"']+)["']/i), t = clean(m[2]).trim(); if (!t) continue; var url = abs(m[1].replace(/&amp;/g, '&'), base), season = (t.match(/saison\s*([0-9]+)/i) || [])[1]; out.push({ id: idOf(url) || url, title: t, url: url, cover: im ? abs(im[1], base) : '', type: 'anime', sourceId: SOURCE_ID, season: season ? Number(season) : 1 }); }
  if (!out.length) { var sr = /search-item[\s\S]*?location\.href\s*=\s*'([^']+)'[\s\S]*?<img[\s\S]*?alt='([^']+)'/gi, sm; while ((sm = sr.exec(html || ''))) { var su = abs(sm[1], base), sc = String(html).slice(sm.index, sm.index + 700), si = sc.match(/<img[^>]*(?:src|data-src)=["']([^"']+)/i); out.push({ id: idOf(su) || su, title: clean(sm[2]).trim(), url: su, cover: si ? abs(si[1], base) : '', type: 'anime', sourceId: SOURCE_ID }); } }
  var seen = {}; return out.filter(function (x) { if (seen[x.url]) return false; seen[x.url] = true; return true; });
}
function getInfo() { return { name: 'French-Manga', lang: 'fr', baseUrl: SITE, logo: SITE + '/favicon.ico', type: 'anime', version: '1.0.1' }; }
function search(query, page, opts) { if (!String(query || '').trim()) return Promise.resolve([]); return request('/engine/ajax/search.php', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' }, body: 'query=' + esc(query) + '&page=' + (page || 1) }).then(function (r) { if (!r) return []; var h = responseBody(r), list = cards(h, SITE); if (!list.length) return request('/index.php?do=search&subaction=search&story=' + esc(query), {}).then(function (r2) { return r2 ? cards(responseBody(r2), SITE) : []; }); return list; }); }
function popular(opts) { var q = ['naruto', 'one piece', 'solo leveling']; return search(q[(opts && opts.dateRange || 0) % q.length], 1, opts); }
function detailTitle(h, url) { var m = h.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i) || h.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i); return clean(m ? m[1] : titleFromUrl(url)).replace(/\s+/g, ' ').trim(); }
function detailData(h, url) { var title = detailTitle(h, url), im = h.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i), dm = h.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i), yr = (h.match(/(?:19|20)\d{2}/) || [])[0]; return { title: title, cover: im ? abs(im[1], url) : '', description: dm ? clean(dm[1]) : '', year: yr ? Number(yr) : undefined, genres: [] }; }
function parseEpisodeJson(data, pageUrl, fallbackTitle) { var out = []; Object.keys(data || {}).forEach(function (lang) { var group = data[lang]; if (!group || typeof group !== 'object') return; Object.keys(group).forEach(function (n) { var ep = group[n], links = []; if (ep && typeof ep === 'object') Object.keys(ep).forEach(function (k) { if (typeof ep[k] === 'string' && /^https?:\/\//i.test(ep[k])) links.push(ep[k]); }); else if (typeof ep === 'string') links.push(ep); if (links.length) out.push({ id: pageUrl + '|s=1|e=' + n + '|lang=' + lang, number: Number(n) || 0, season: 1, title: lang.toUpperCase() + ' · Épisode ' + n, url: pageUrl, sourceId: SOURCE_ID, lang: lang, links: uniq(links), description: fallbackTitle || '' }); }); }); return out; }
function getDetail(url) { return request(url, {}).then(function (r) { if (!r) return null; var h = responseBody(r), d = detailData(h, url), id = idOf(url); return request('/engine/ajax/manga_episodes_api.php?id=' + esc(id), {}).then(function (er) { var data = er ? parseJson(er) : null, eps = data ? parseEpisodeJson(data, url, d.title) : []; return { id: id || url, title: d.title, url: url, cover: d.cover, description: d.description, year: d.year, genres: d.genres, type: /film/i.test(d.title) ? 'movie' : 'anime', sourceId: SOURCE_ID, episodes: eps }; }); }); }
function getEpisodes(url) { return getDetail(url).then(function (d) { return d ? d.episodes || [] : []; }); }
function getVideoSources(episodeUrl) { var raw = String(episodeUrl || ''), parts = raw.split('|'), page = parts[0], lang = (raw.match(/\|lang=([^|]+)/i) || [])[1], ep = (raw.match(/\|e=([^|]+)/i) || [])[1]; return request('/engine/ajax/manga_episodes_api.php?id=' + esc(idOf(page)), {}).then(function (r) { var data = r ? parseJson(r) : null, group = data && data[lang || 'vf'], item = group && group[ep || '1'], links = []; if (item && typeof item === 'object') Object.keys(item).forEach(function (k) { if (/^https?:\/\//i.test(item[k])) links.push(item[k]); }); return uniq(links).reduce(function (p, u) { return p.then(function (arr) { return extractVideo(u, { headers: { Referer: page, 'User-Agent': UA } }).then(function (x) { return arr.concat(x || []); }).catch(function () { return arr; }); }); }, Promise.resolve([])); }); }
