var SOURCE_ID = 'movix';
var SITE = 'https://movix.fun';
var API_BASES = ['https://api.movix.fun', 'https://api.movix.show', 'https://api.movix.cash'];
var TMDB = 'https://api.themoviedb.org/3';
var TMDB_KEY = 'f3d757824f08ea2cff45eb8f47ca3a1e';
var IMG = 'https://image.tmdb.org/t/p';
var UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/125 Safari/537.36';
function enc(s) { return encodeURIComponent(String(s || '')); }
function body(r) { return r && (r.body || (typeof r.text === 'function' ? r.text() : '')) || ''; }
function json(r) { try { return JSON.parse(body(r)); } catch (_) { return null; } }
function abs(u, b) { try { return absUrl(u, b); } catch (_) { return u; } }
function clean(s) { return htmlText(String(s || '')); }
function uniq(a) { var o = [], s = {}; (a || []).forEach(function (x) { if (x && !s[x]) { s[x] = 1; o.push(x); } }); return o; }
function hostOf(u) { var m = String(u || '').match(/^https?:\/\/([^/]+)/i); return m ? m[1].replace(/^www\./i, '').toLowerCase() : ''; }
function hostLabel(h) { var s = String(h || '').toLowerCase(); if (s === 'premium' || /fsvid/.test(s)) return 'FSVID'; if (/vidzy/.test(s)) return 'VIDZY'; if (/uqload/.test(s)) return 'UQLOAD'; if (/dood/.test(s)) return 'DOOD'; if (/voe/.test(s)) return 'VOE'; if (/filmoon|filemoon/.test(s)) return 'FILEMOON'; if (/mixdrop/.test(s)) return 'MIXDROP'; if (/lulu/.test(s)) return 'LULU'; if (/vidshareup|vidhsareup/.test(s)) return 'VIDSHAREUP'; return s ? s.toUpperCase() : 'PLAYER'; }
function langLabel(l) { var s = String(l || '').toLowerCase(); if (s === 'vf' || s === 'default' || s === 'vfq' || s === 'vff') return 'VF'; if (s === 'vostfr' || s === 'vo') return s === 'vo' ? 'VO' : 'VOSTFR'; return s ? s.toUpperCase() : 'VF'; }
function qualityOf(v, fallback) { var s = String(v || '').trim(); if (/^(unknown|auto|default|original|source)$/i.test(s)) s = ''; if (/4k|uhd/i.test(s)) return '2160p'; var m = s.match(/(?:2160|1440|1080|720|576|540|480|360|240)\s*p?/i); if (m) return /p$/i.test(m[0]) ? m[0].toLowerCase() : m[0] + 'p'; if (/full\s*hd|fhd/i.test(s)) return '1080p'; if (/\bhd\b/i.test(s)) return 'HD'; if (/\bsd\b/i.test(s)) return 'SD'; return s || fallback || 'HD'; }
function decorate(source, meta, ref) { var m = meta || {}, server = m.server || hostOf(source && source.url) || 'player', lang = langLabel(m.lang), q = qualityOf(m.quality, qualityOf(source && source.quality, 'HD')); var out = Object.assign({}, source || {}); out.quality = q; out.label = m.label || ('[' + lang + '] ' + hostLabel(server)); out.headers = Object.assign({}, source && source.headers || {}, { Referer: (source && source.headers && source.headers.Referer) || ref || SITE, 'User-Agent': UA }); return out; }
function image(path, size) { return path ? IMG + '/' + (size || 'w500') + path : ''; }
function tmdb(path, params) { var q = Object.assign({ api_key: TMDB_KEY, language: 'fr-FR', include_image_language: 'fr,en,null' }, params || {}), qs = Object.keys(q).map(function (k) { return enc(k) + '=' + enc(q[k]); }).join('&'); return fetch(TMDB + '/' + String(path).replace(/^\//, '') + '?' + qs, { headers: { 'User-Agent': UA }, timeoutMs: 15000 }).then(function (r) { return r && r.status >= 200 && r.status < 400 ? json(r) : null; }).catch(function () { return null; }); }
function api(path, i) { i = i || 0; if (i >= API_BASES.length) return Promise.resolve(null); return fetch(API_BASES[i] + '/' + String(path).replace(/^\//, ''), { headers: { 'User-Agent': UA, Origin: SITE, Referer: SITE + '/' }, timeoutMs: 12000 }).then(function (r) { if (r && r.status >= 200 && r.status < 400) return json(r); return api(path, i + 1); }).catch(function () { return api(path, i + 1); }); }
function kind(item) { return item.media_type === 'tv' || item.first_air_date != null ? 'tv' : 'movie'; }
function result(x) { var k = kind(x), title = k === 'tv' ? (x.name || x.original_name) : (x.title || x.original_title); return { id: k + '/' + x.id, title: title || 'Movix', url: 'movix://' + k + '/' + x.id, cover: image(x.poster_path), type: 'movie', sourceId: SOURCE_ID, year: String(k === 'tv' ? x.first_air_date || '' : x.release_date || '').slice(0, 4) || undefined, description: clean(x.overview || '') }; }
function getInfo() { return { name: 'Movix', lang: 'fr', baseUrl: SITE, logo: SITE + '/favicon.ico', type: 'movie', version: '1.0.7' }; }
function search(query, page, opts) { if (!String(query || '').trim()) return Promise.resolve([]); return tmdb('search/multi', { query: query, page: page || 1, include_adult: 'false' }).then(function (d) { return (d && d.results || []).filter(function (x) { return x.media_type === 'movie' || x.media_type === 'tv'; }).map(result); }); }
function popular(opts) { return tmdb('trending/all/week', {}).then(function (d) { return (d && d.results || []).filter(function (x) { return x.media_type === 'movie' || x.media_type === 'tv'; }).map(result); }); }
function getHome(opts) { return popular(opts).then(function (items) { return [{ title: 'Tendances Movix', items: items || [] }]; }); }
function movieDetail(d, url) { return { id: 'movie/' + d.id, title: d.title || d.original_title || 'Movix', url: url, cover: image(d.poster_path), background: image(d.backdrop_path, 'w1280'), description: clean(d.overview || ''), year: String(d.release_date || '').slice(0, 4) || undefined, genres: (d.genres || []).map(function (x) { return x.name; }), type: 'movie', sourceId: SOURCE_ID, episodes: [{ id: url + '|movie', number: 1, season: 1, title: 'Film', url: url, sourceId: SOURCE_ID }] }; }
function tvDetail(d, url) { var seasons = (d.seasons || []).map(function (s) { return s.season_number; }).filter(function (n) { return n > 0; }); return seasonChain(d.id, seasons, 0, image(d.poster_path), url, []).then(function (eps) { return { id: 'tv/' + d.id, title: d.name || d.original_name || 'Movix', url: url, cover: image(d.poster_path), background: image(d.backdrop_path, 'w1280'), description: clean(d.overview || ''), year: String(d.first_air_date || '').slice(0, 4) || undefined, genres: (d.genres || []).map(function (x) { return x.name; }), type: 'movie', sourceId: SOURCE_ID, episodes: eps }; }); }
function seasonChain(id, seasons, ix, poster, url, out) { if (ix >= seasons.length) return Promise.resolve(out); return tmdb('tv/' + id + '/season/' + seasons[ix]).then(function (d) { (d && d.episodes || []).forEach(function (e) { if (e.episode_number > 0) out.push({ id: url + '|s=' + seasons[ix] + '|e=' + e.episode_number, number: e.episode_number, season: seasons[ix], title: clean(e.name || ('Épisode ' + e.episode_number)), url: url, sourceId: SOURCE_ID, cover: image(e.still_path) || poster, description: clean(e.overview || '') }); }); return seasonChain(id, seasons, ix + 1, poster, url, out); }); }
function getDetail(url) { var m = String(url).match(/movix:\/\/(movie|tv)\/(\d+)/i) || String(url).match(/\b(movie|tv)\/(\d+)/i); if (!m) return Promise.resolve(null); return tmdb(m[1] + '/' + m[2], { append_to_response: 'credits,videos,images,external_ids,recommendations' }).then(function (d) { return !d ? null : m[1] === 'tv' ? tvDetail(d, url) : movieDetail(d, url); }); }
function getEpisodes(url) { return getDetail(url).then(function (d) { return d ? d.episodes || [] : []; }); }
function collectStrings(v, out) { if (!v) return; if (typeof v === 'string') { if (/^https?:\/\//i.test(v)) out.push(v); return; } if (typeof v === 'object') Object.keys(v).forEach(function (k) { collectStrings(v[k], out); }); }
function bytesFromBase64(s) { try { if (typeof base64ToBytes === 'function') return Array.from(base64ToBytes(s)); if (typeof atob === 'function') { var t = atob(s), a = []; for (var i = 0; i < t.length; i++) a.push(t.charCodeAt(i)); return a; } } catch (_) {} return []; }
function decodeFsvid(h) { var m = String(h || '').match(/var\s+k\s*=\s*\[([0-9,\s]+)]\s*,\s*b\s*=\s*atob\(s\)[\s\S]*?\}\)\(\s*["']([A-Za-z0-9+/_=-]+)["']\s*\)/i); if (!m) return ''; var key = m[1].split(',').map(function (x) { return Number(x.trim()); }).filter(function (x) { return isFinite(x); }), encrypted = bytesFromBase64(m[2]), out = ''; if (!key.length || !encrypted.length) return ''; for (var i = 0; i < encrypted.length; i++) out += String.fromCharCode(encrypted[i] ^ key[i % key.length]); return out.trim(); }
function unpackText(s) {
  s = String(s || '');
  function decode(payload, radix, dict) {
    function rN(t) { var n = 0; for (var i = 0; i < t.length; i++) { var c = t.charCodeAt(i); n = n * radix + (c <= 57 ? c - 48 : c >= 97 ? c - 87 : c - 29); } return n; }
    return payload.replace(/[0-9A-Za-z]+/g, function (k) { var i = rN(k); return i < dict.length && dict[i] !== '' ? dict[i] : k; });
  }
  var m = s.match(/\}\(\s*'((?:\\.|[^'])*)'\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*'((?:\\.|[^'])*)'\.split\('\|'\)/);
  if (!m) return s;
  var payload = m[1].replace(/\\'/g, "'").replace(/\\\\/g, '\\\\');
  var dict = m[4].replace(/\\'/g, "'").replace(/\\\\/g, '\\\\').split('|');
  return decode(payload, Number(m[2]), dict);
}
function directMedia(u, ref, meta) {
  function make(stream, source) { stream = String(stream || '').replace(/\\\//g, '/'); if (stream.indexOf('//') === 0) stream = 'https:' + stream; var allowNoExt = /mixdrop/i.test(u) && /^https?:\/\//i.test(stream); if (!/^https?:\/\//i.test(stream) || /\/troll\/|test-videos|big[_-]?buck[_-]bunny|sample-videos|example\.com|localhost/i.test(stream) || (!allowNoExt && !/\.(?:m3u8|mp4)(?:\?|$)/i.test(stream))) return []; var out = { url: stream, quality: qualityOf((meta || {}).quality, (stream.match(/(?:2160|1440|1080|720|576|540|480|360|240)p?/i) || [])[0]), container: /\.m3u8(?:\?|$)/i.test(stream) ? 'hls' : 'mp4', headers: { Referer: source || ref || SITE, Origin: SITE, 'User-Agent': UA }, kind: 'sub' }; return [decorate(out, meta, source || ref)]; }
  function pick(h) { var raw = String(h || ''), decoded = decodeFsvid(raw), unpacked = unpackText(raw); if (unpacked === raw && typeof unpackJs === 'function') unpacked = unpackJs(raw); var texts = [decoded, unpacked, raw], re = /(?:file|src|hls|url|sources?\s*\[?0?\]?\.file)\s*[:=]\s*["']([^"']+(?:\.m3u8|\.mp4)(?:\?[^"']*)?)["']/i, any = /https?:\/\/[^"'\s]+\.(?:m3u8|mp4)(?:\?[^"'\s]*)?/i; for (var i = 0; i < texts.length; i++) { var core = texts[i].match(/Core\.wurl\s*=\s*["']([^"']+)["']/i); if (core) return core[1]; var m = texts[i].match(re) || texts[i].match(any); if (m) return m[1] || m[0]; } return ''; }
  function peel(html, source) { var stream = pick(html); if (stream) return Promise.resolve(make(stream, source)); var redirect = String(html || '').match(/<iframe[^>]+src=["']([^"']+)["']/i) || String(html || '').match(/(?:window\.location(?:\.href|\.replace)?|location\.href)\s*=?\s*\(?["']([^"']+)["']/i); if (!redirect || !redirect[1]) return Promise.resolve([]); var next = abs(redirect[1].replace(/\\\//g, '/'), source || u); if (!next || next === source) return Promise.resolve([]); return resolveOne(next, source || u, meta); }
  return fetch(u, { headers: { Referer: ref || SITE + '/', Origin: SITE, 'User-Agent': UA }, timeoutMs: 20000 }).then(function (r) { return r ? peel(body(r), u) : []; }).catch(function () { return []; });
}
function randomToken(n) { var a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', s = ''; for (var i = 0; i < (n || 10); i++) s += a.charAt(Math.floor(Math.random() * a.length)); return s; }
function doodVideo(u, ref, meta) { var embed = String(u || '').replace('/d/', '/e/'); return fetch(embed, { headers: { Referer: ref || SITE, Origin: SITE, 'User-Agent': UA }, timeoutMs: 20000 }).then(function (r) { var h = body(r), finalUrl = r && r.url || embed, m = h.match(/\/pass_md5\/[^'" ]+/i); if (!m) return []; var base = finalUrl.match(/^https?:\/\/[^/]+/i); if (!base) return []; return fetch(base[0] + m[0], { headers: { Referer: finalUrl, 'User-Agent': UA }, timeoutMs: 12000 }).then(function (p) { var prefix = body(p).trim(); if (!prefix) return []; var out = { url: prefix + randomToken(10) + '?token=' + m[0].slice(m[0].lastIndexOf('/') + 1) + '&expiry=' + Date.now(), quality: qualityOf((meta || {}).quality, 'HD'), container: 'mp4', headers: { Referer: base[0] + '/', Origin: SITE, 'User-Agent': UA }, kind: 'sub' }; return [decorate(out, meta, finalUrl)]; }); }).catch(function () { return []; }); }
function resolveOne(u, ref, meta) { var host = hostOf(u); if (/^(dood(?:stream)?\.(?:to|so|ws|la|li|cx|sh|wf|yt|pm|re|watch|work)|dsvplay\.com|ds2(?:play|video)\.com|d000d\.com|d0000d\.com|dooood\.com|vide0\.net)$/.test(host)) return doodVideo(u, ref, meta); if (/^(fsvid\.(?:lol|in|live)|vidzy\.(?:cc|org|live)|uqload\.(?:is|com|co|to|cx)|vidhsareup\.(?:fun|io)|vidshareup\.(?:fun|io)|kakaflix\.[^/]+|bysebuho\.com|embedseek\.com|mixdrop\.(?:ag|to|co)|luluvdo\.com|lulustream\.com|luluvdoo\.com|luluvid\.com|voe\.(?:sx|to|st)|filemoon\.(?:sx|in)|vidmoly\.(?:to|me)|vidstream\.pro|vidcdn\.)$/.test(host)) return directMedia(u, ref, meta); return extractVideo(u, { headers: { Referer: ref || SITE + '/', Origin: SITE, 'User-Agent': UA } }).then(function (x) { return (x || []).map(function (s) { return decorate(s, meta, ref); }); }).catch(function () { return []; }); }
function limited(p, ms) { return Promise.race([p, new Promise(function (resolve) { setTimeout(function () { resolve([]); }, ms || 9000); })]); }
function resolveLinks(candidates, ref) { var seen = {}, unique = (candidates || []).filter(function (c) { var key = c.url + '|' + c.server + '|' + c.lang; if (seen[key]) return false; seen[key] = 1; return true; }); return Promise.all(unique.map(function (c) { return limited(resolveOne(c.url, ref, { server: c.server, lang: c.lang, quality: c.quality }), 9000).catch(function () { return []; }); })).then(function (groups) { return groups.reduce(function (out, x) { return out.concat(x || []); }, []); }); }
function parseCandidates(d, type, episode) { var out = []; function add(url, server, lang, quality) { if (typeof url === 'string' && /^https?:\/\//i.test(url)) out.push({ url: url, server: server || hostOf(url), lang: lang || 'vf', quality: quality || 'HD' }); } function group(v, lang) { if (Array.isArray(v)) v.forEach(function (item) { if (item && typeof item === 'object') add(item.url, item.player || item.name || item.server, lang, item.quality); else add(item, '', lang, 'HD'); }); else if (v && typeof v === 'object') Object.keys(v).forEach(function (k) { var item = v[k]; if (typeof item === 'string') add(item, k, lang, 'HD'); else if (item && typeof item === 'object') add(item.url, item.player || item.name || k, lang, item.quality); }); }
  if (!d || typeof d !== 'object') return out; var groups = d.players || d.links; if (groups && typeof groups === 'object') Object.keys(groups).forEach(function (lang) { group(groups[lang], lang); }); if (type === 'tv' && d.episodes) { var ep = d.episodes[String(episode)] || d.episodes[episode]; if (ep && ep.languages) Object.keys(ep.languages).forEach(function (lang) { group(ep.languages[lang], lang); }); if (ep) ['vf','vostfr','vo','VFF','VFQ','VOSTFR','Default'].forEach(function (lang) { if (ep[lang]) group(ep[lang], lang); }); } ['vf','vostfr','vo','VFF','VFQ','VOSTFR','Default'].forEach(function (lang) { if (d[lang]) group(d[lang], lang); }); return out; }
function getVideoSources(episodeUrl) { var raw = String(episodeUrl || ''), m = raw.match(/movix:\/\/(movie|tv)\/(\d+)/i), id = m ? m[2] : '', type = m ? m[1] : 'movie', s = (raw.match(/\|s=(\d+)/) || [])[1], e = (raw.match(/\|e=(\d+)/) || [])[1], paths = type === 'tv' ? ['/api/fstream/tv/' + id + '/season/' + s, '/api/wiflix/tv/' + id + '/' + s, '/api/cpasmal/tv/' + id + '/' + s] : ['/api/fstream/movie/' + id, '/api/links/movie/' + id, '/api/wiflix/movie/' + id, '/api/j1f/movie/' + id, '/api/cpasmal/movie/' + id]; function one(ix, collected) { if (ix >= paths.length) return resolveLinks(collected, SITE); return api(paths[ix]).then(function (d) { var got = parseCandidates(d, type, e); if (type === 'tv' && e) { var filtered = got.filter(function (c) { return c.url.indexOf(String(e)) >= 0 || c.url.indexOf('/e/') >= 0 || c.url.indexOf('/embed') >= 0 || c.server; }); if (filtered.length) got = filtered; } return one(ix + 1, collected.concat(got)); }); } return one(0, []); }
